version: '3.4'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    ports:
      - "8891:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.20.0
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
  sentence:
    image: robbe7730/sentence-service:1.0.0
    environment:
      LOG_LEVEL: "INFO"
      SENTENCE_URI_BASE: "https://gelinkt-rollenspelen.robbevanherck.be/sentence/"
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: unless-stopped
    logging: *default-logging
